/**
 * Next.js App Router handler for OnClaw.
 *
 * Basic usage:
 * ```ts
 * // app/api/onclaw/[...onclaw]/route.ts
 * import { createOnClawHandler } from "onclaw/next";
 * export const { GET, POST } = createOnClawHandler({
 *   provider: "anthropic",
 *   apiKey: process.env.ANTHROPIC_API_KEY!,
 * });
 * ```
 *
 * With context API (generated by `npx onclaw init`):
 * ```ts
 * import { createOnClawHandler } from "onclaw/next";
 * import { createContext } from "@/onclaw/context";
 *
 * export const { GET, POST } = createOnClawHandler({
 *   provider: "anthropic",
 *   apiKey: process.env.ANTHROPIC_API_KEY!,
 *   context: createContext(),
 *   auth: async (req) => {
 *     const session = await getServerSession(req);
 *     if (!session?.user) throw new Error("Unauthorized");
 *     return { userId: session.user.id, role: session.user.role };
 *   },
 * });
 * ```
 */

import { buildRuntimeSystemPrompt, type ProjectManifest } from "./cli/prompts";
import * as fs from "fs";
import * as path from "path";

/** Safe JSON response helper — avoids issues with Response.json() in some Next.js versions */
function jsonResponse(data: unknown, init?: { status?: number; headers?: Record<string, string> }): Response {
  return new Response(JSON.stringify(data), {
    status: init?.status ?? 200,
    headers: {
      "Content-Type": "application/json",
      ...init?.headers,
    },
  });
}

// ─── Types ──────────────────────────────────────────────

interface OnClawUser {
  userId: string;
  role?: string;
  [key: string]: unknown;
}

interface ContextQuery {
  (...args: any[]): Promise<any>;
}

interface ContextAction {
  (...args: any[]): Promise<any>;
}

interface OnClawContext {
  queries: Record<string, ContextQuery>;
  actions?: Record<string, ContextAction>;
}

interface HandlerConfig {
  /** LLM provider */
  provider: "anthropic" | "openai" | "openclaw";
  /** API key (not needed for "openclaw" provider) */
  apiKey?: string;
  /** Model override */
  model?: string;
  /** Enable streaming responses (SSE) */
  streaming?: boolean;
  /** OpenClaw config path override */
  openclawConfigPath?: string;

  // ─── Context API (new) ────────────────────────────────
  /** Data context — what generated components can query/mutate */
  context?: OnClawContext;
  /** Auth callback — extracts user from request. Throw to reject. */
  auth?: (req: Request) => Promise<OnClawUser> | OnClawUser;
  /** Authorization callback — controls who can do what */
  authorize?: (user: OnClawUser, action: "generate" | "server-mutate" | "read") => boolean | Promise<boolean>;
  /** Path to .onclaw/project.json (auto-detected if not set) */
  manifestPath?: string;
  /** Server-side mutation config */
  mutations?: {
    /** Enable server-side file mutations */
    enabled: boolean;
    /** Directory for generated files (default: src/onclaw/generated) */
    outputDir?: string;
    /** Require approval before writing files */
    requireApproval?: boolean;
    /** Max file size per mutation in bytes (default: 50KB) */
    maxFileSize?: number;
    /** Protected path patterns (glob) that cannot be written */
    protectedPatterns?: string[];
  };
  /** Rate limiting */
  rateLimit?: {
    /** Max generations per window per user */
    maxGenerations: number;
    /** Window in milliseconds */
    windowMs: number;
  };
}

/** Resolved config after OpenClaw auto-detection */
interface ResolvedConfig {
  provider: "anthropic" | "openai";
  apiKey: string;
  model?: string;
  streaming?: boolean;
}

// ─── Rate limit store (in-memory, per-process) ──────────

const rateLimitStore = new Map<string, number[]>();

function checkRateLimit(userId: string, config: HandlerConfig): boolean {
  if (!config.rateLimit) return true;
  const now = Date.now();
  const key = `rl:${userId}`;
  const timestamps = (rateLimitStore.get(key) || []).filter(
    (t) => now - t < config.rateLimit!.windowMs
  );
  if (timestamps.length >= config.rateLimit.maxGenerations) return false;
  timestamps.push(now);
  rateLimitStore.set(key, timestamps);
  return true;
}

// ─── Manifest loading ───────────────────────────────────

let cachedManifest: ProjectManifest | null = null;

function loadManifest(config: HandlerConfig): ProjectManifest | null {
  if (cachedManifest) return cachedManifest;
  try {
    const manifestPath =
      config.manifestPath ||
      path.join(process.cwd(), ".onclaw", "project.json");
    const raw = fs.readFileSync(manifestPath, "utf-8");
    cachedManifest = JSON.parse(raw);
    return cachedManifest;
  } catch {
    return null;
  }
}

// ─── Context execution ──────────────────────────────────

/**
 * Execute a context query/action on behalf of a generated component.
 * This runs server-side — the generated client code calls an API endpoint
 * which routes here.
 */
async function executeContextCall(
  context: OnClawContext,
  type: "query" | "action",
  name: string,
  args: any[]
): Promise<any> {
  const source = type === "query" ? context.queries : context.actions;
  if (!source || !(name in source)) {
    throw new Error(`Unknown ${type}: ${name}`);
  }
  // Execute with a timeout
  const fn = source[name];
  const result = await Promise.race([
    fn(...args),
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error(`${type} "${name}" timed out`)), 5000)
    ),
  ]);
  return result;
}

// ─── Main handler ───────────────────────────────────────

export function createOnClawHandler(config: HandlerConfig) {
  const resolved = resolveOpenClawConfig(config);

  async function POST(req: Request): Promise<Response> {
    try {
      const url = new URL(req.url);
      const pathSegments = url.pathname.split("/").filter(Boolean);
      const lastSegment = pathSegments[pathSegments.length - 1];

      // Route: /api/onclaw/context — execute a context query/action
      if (lastSegment === "context") {
        return handleContextCall(req, config);
      }

      // Route: /api/onclaw/manifest — return the project manifest (for client-side enrichment)
      if (lastSegment === "manifest") {
        return handleManifest(config);
      }

      // Route: /api/onclaw/generate or /api/onclaw/stream — LLM generation
      return handleGenerate(req, config, resolved);
    } catch (err: any) {
      console.error("[OnClaw] Handler error:", err);
      return jsonResponse(
        { error: err.message || "Internal server error" },
        { status: 500 }
      );
    }
  }

  async function GET(req: Request): Promise<Response> {
    const url = new URL(req.url);
    const pathSegments = url.pathname.split("/").filter(Boolean);
    const lastSegment = pathSegments[pathSegments.length - 1];

    if (lastSegment === "manifest") {
      return handleManifest(config);
    }

    return new Response("OnClaw API", { status: 200 });
  }

  return { GET, POST };
}

// ─── Route handlers ─────────────────────────────────────

async function handleContextCall(
  req: Request,
  config: HandlerConfig
): Promise<Response> {
  // Auth check
  if (config.auth) {
    try {
      const user = await config.auth(req);
      if (config.authorize) {
        const allowed = await config.authorize(user, "read");
        if (!allowed)
          return new Response(JSON.stringify({ error: "Forbidden" }), { status: 403, headers: { "Content-Type": "application/json" } });
      }
    } catch {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { "Content-Type": "application/json" } });
    }
  }

  if (!config.context) {
    return jsonResponse({ error: "No context API configured" }, { status: 400 });
  }

  try {
    const { type, name, args } = await req.json();
    const result = await executeContextCall(config.context, type, name, args || []);

    // Cap response size (10MB)
    const json = JSON.stringify(result);
    if (json.length > 10 * 1024 * 1024) {
      return jsonResponse({ error: "Response too large. Use filters to narrow the query." }, { status: 413 });
    }

    return new Response(JSON.stringify({ data: result }), { headers: { "Content-Type": "application/json" } });
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), { status: 400, headers: { "Content-Type": "application/json" } });
  }
}

function handleManifest(config: HandlerConfig): Response {
  const manifest = loadManifest(config);
  if (!manifest) {
    return jsonResponse({ error: "No project manifest found. Run `npx onclaw init`." }, { status: 404 });
  }
  // Return a safe subset — don't expose internal paths or sensitive info
  const safe = {
    framework: manifest.framework,
    orm: manifest.orm,
    database: manifest.database,
    styling: manifest.styling,
    queries: Array.isArray(manifest.queries)
      ? manifest.queries.map((q: any) => ({ name: q.name, description: q.description, params: q.params, returns: q.returns }))
      : manifest.queries,
    actions: Array.isArray(manifest.actions)
      ? manifest.actions.map((a: any) => ({ name: a.name, description: a.description, params: a.params }))
      : manifest.actions,
    slots: manifest.slots,
    uiPatterns: manifest.uiPatterns,
  };
  return new Response(JSON.stringify(safe), { headers: { "Content-Type": "application/json" } });
}

async function handleGenerate(
  req: Request,
  config: HandlerConfig,
  resolved: ResolvedConfig
): Promise<Response> {
  // Auth check
  let user: OnClawUser | undefined;
  if (config.auth) {
    try {
      user = await config.auth(req);
      if (config.authorize) {
        const allowed = await config.authorize(user, "generate");
        if (!allowed)
          return new Response(JSON.stringify({ error: "Forbidden" }), { status: 403, headers: { "Content-Type": "application/json" } });
      }
    } catch {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { "Content-Type": "application/json" } });
    }
  }

  // Rate limit check
  if (user && !checkRateLimit(user.userId, config)) {
    return jsonResponse({ error: "Rate limit exceeded. Try again later." }, { status: 429 });
  }

  const body = await req.json();
  let { messages, max_tokens = 4096, stream: clientRequestsStream } = body;
  const useStream = resolved.streaming || clientRequestsStream;

  // Enrich system prompt with project manifest if available
  const manifest = loadManifest(config);
  if (manifest) {
    const enrichedSystemPrompt = buildRuntimeSystemPrompt(manifest);
    // Prepend or replace the system message
    const hasSystem = messages.some((m: any) => m.role === "system");
    if (hasSystem) {
      messages = messages.map((m: any) =>
        m.role === "system"
          ? { ...m, content: enrichedSystemPrompt + "\n\n" + m.content }
          : m
      );
    } else {
      messages = [
        { role: "system", content: enrichedSystemPrompt },
        ...messages,
      ];
    }

    // Add context API info — tell the LLM what queries are available
    if (config.context) {
      const contextInfo = [
        "\n## Available at Runtime",
        "The generated component will receive `ctx` as a prop with:",
        ...Object.keys(config.context.queries).map(
          (q) => `- ctx.queries.${q}()`
        ),
        ...(config.context.actions
          ? Object.keys(config.context.actions).map(
              (a) => `- ctx.actions.${a}()`
            )
          : []),
        "",
        "To fetch data in a component, use: `const data = await ctx.queries.functionName(filters)`",
        "Wrap data fetching in React.useState + React.useEffect patterns.",
      ].join("\n");

      // Append to system message
      messages = messages.map((m: any) =>
        m.role === "system"
          ? { ...m, content: m.content + contextInfo }
          : m
      );
    }
  }

  if (resolved.provider === "anthropic") {
    return useStream
      ? handleAnthropicStream(messages, max_tokens, resolved)
      : handleAnthropic(messages, max_tokens, resolved);
  }

  return useStream
    ? handleOpenAIStream(messages, max_tokens, resolved)
    : handleOpenAI(messages, max_tokens, resolved);
}

// ─── Provider resolution ────────────────────────────────

function resolveOpenClawConfig(config: HandlerConfig): ResolvedConfig {
  if (config.provider !== "openclaw") {
    return {
      provider: config.provider,
      apiKey: config.apiKey!,
      model: config.model,
      streaming: config.streaming,
    };
  }

  let primaryModel = config.model || "";
  if (!primaryModel) {
    try {
      const configPath =
        config.openclawConfigPath ||
        process.env.OPENCLAW_CONFIG_PATH ||
        path.join(process.env.HOME || "~", ".openclaw", "openclaw.json");
      const raw = fs.readFileSync(configPath, "utf-8");
      const ocConfig = JSON.parse(raw);
      primaryModel = ocConfig?.agents?.defaults?.model?.primary || "";
    } catch {
      // Fall through
    }
  }

  let provider: "anthropic" | "openai" = "anthropic";
  let model = config.model;

  if (primaryModel.startsWith("anthropic/")) {
    provider = "anthropic";
    const modelId = primaryModel.replace("anthropic/", "");
    model = model || mapAnthropicModel(modelId);
  } else if (primaryModel.startsWith("openai/")) {
    provider = "openai";
    model = model || primaryModel.replace("openai/", "");
  } else if (primaryModel.startsWith("google/")) {
    provider = "anthropic";
    model = model || "claude-sonnet-4-20250514";
  }

  const apiKey =
    provider === "anthropic"
      ? process.env.ANTHROPIC_API_KEY ||
        process.env.OPENCLAW_ANTHROPIC_KEY ||
        ""
      : process.env.OPENAI_API_KEY || process.env.OPENCLAW_OPENAI_KEY || "";

  if (!apiKey) {
    throw new Error(
      `OnClaw: No API key found for ${provider}. ` +
        `Set ${provider === "anthropic" ? "ANTHROPIC_API_KEY" : "OPENAI_API_KEY"} in your environment.`
    );
  }

  return { provider, apiKey, model, streaming: config.streaming };
}

function mapAnthropicModel(id: string): string {
  const map: Record<string, string> = {
    "claude-opus-4-6": "claude-opus-4-20250514",
    "claude-sonnet-4": "claude-sonnet-4-20250514",
  };
  return map[id] || id;
}

// ─── Anthropic non-streaming ────────────────────────────

async function handleAnthropic(
  messages: { role: string; content: string }[],
  max_tokens: number,
  config: ResolvedConfig
): Promise<Response> {
  const systemMsg = messages.find((m) => m.role === "system")?.content || "";
  const userMsgs = messages.filter((m) => m.role !== "system");

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": config.apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: config.model || "claude-sonnet-4-20250514",
      max_tokens,
      system: systemMsg,
      messages: userMsgs,
    }),
  });

  if (!res.ok) return new Response(await res.text(), { status: res.status });

  const data = await res.json();
  const content = data.content?.[0]?.text || "";
  return new Response(JSON.stringify({ choices: [{ message: { content } }] }), { headers: { "Content-Type": "application/json" } });
}

// ─── Anthropic streaming ────────────────────────────────

async function handleAnthropicStream(
  messages: { role: string; content: string }[],
  max_tokens: number,
  config: ResolvedConfig
): Promise<Response> {
  const systemMsg = messages.find((m) => m.role === "system")?.content || "";
  const userMsgs = messages.filter((m) => m.role !== "system");

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": config.apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: config.model || "claude-sonnet-4-20250514",
      max_tokens,
      stream: true,
      system: systemMsg,
      messages: userMsgs,
    }),
  });

  if (!res.ok) return new Response(await res.text(), { status: res.status });

  const reader = res.body!.getReader();
  const decoder = new TextDecoder();

  const stream = new ReadableStream({
    async pull(controller) {
      let buffer = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) {
          controller.enqueue(new TextEncoder().encode("data: [DONE]\n\n"));
          controller.close();
          return;
        }
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed.startsWith("data: ")) continue;
          const payload = trimmed.slice(6);
          if (!payload || payload === "[DONE]") continue;
          try {
            const event = JSON.parse(payload);
            if (event.type === "content_block_delta" && event.delta?.text) {
              controller.enqueue(
                new TextEncoder().encode(
                  `data: ${JSON.stringify({ token: event.delta.text })}\n\n`
                )
              );
            }
          } catch {}
        }
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
}

// ─── OpenAI non-streaming ───────────────────────────────

async function handleOpenAI(
  messages: { role: string; content: string }[],
  max_tokens: number,
  config: ResolvedConfig
): Promise<Response> {
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      model: config.model || "gpt-4o-mini",
      max_tokens,
      messages,
    }),
  });

  if (!res.ok) return new Response(await res.text(), { status: res.status });
  return new Response(JSON.stringify(await res.json()), { headers: { "Content-Type": "application/json" } });
}

// ─── OpenAI streaming ───────────────────────────────────

async function handleOpenAIStream(
  messages: { role: string; content: string }[],
  max_tokens: number,
  config: ResolvedConfig
): Promise<Response> {
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${config.apiKey}`,
    },
    body: JSON.stringify({
      model: config.model || "gpt-4o-mini",
      max_tokens,
      stream: true,
      messages,
    }),
  });

  if (!res.ok) return new Response(await res.text(), { status: res.status });

  const reader = res.body!.getReader();
  const decoder = new TextDecoder();

  const stream = new ReadableStream({
    async pull(controller) {
      let buffer = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) {
          controller.enqueue(new TextEncoder().encode("data: [DONE]\n\n"));
          controller.close();
          return;
        }
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed.startsWith("data: ")) continue;
          const payload = trimmed.slice(6);
          if (!payload || payload === "[DONE]") continue;
          try {
            const event = JSON.parse(payload);
            const token = event.choices?.[0]?.delta?.content;
            if (token) {
              controller.enqueue(
                new TextEncoder().encode(
                  `data: ${JSON.stringify({ token })}\n\n`
                )
              );
            }
          } catch {}
        }
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
}
